# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [4]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [5]:
import numpy as np

class Sudoku:
    
    def __init__(self, sudoku):
        """Sets the initial possible and final values of the sudoku"""
        self.possible_values = np.empty((9,9), dtype=list)
        self.final_values = sudoku
    
    def is_goal(self):
        """Checks if there are any unset cells"""
        if 0 in self.final_values:
            return False
        return True
      
    def set_possible_values(self,row,column,values):
        """Sets the possible values a cell can take """
        self.possible_values[row][column] = values
        return self
    
    def is_invalid(self):
        """Returns true if the length of the list of possible values for any given cell in the sudoku is 0"""
        values = [value for rows in self.possible_values for value in rows if len(value) == 0]
        return len(values)==0
    
    def get_possible_values(self, row, column):
        """Returns a copy of a cell's possible values """
        return self.possible_values[row][column].copy()
    
    def get_final_values(self, row, column):
        """Returns the final value of a given cell"""
        return int(self.final_values[row][column])
    
    def get_final_state(self):
        """Returns the final values if the sudoku is in a goal state"""
        if self.is_goal():
            return self.final_values
        else:
            return -1
        
    def get_singleton_positions(self):
        """Returns a list of coordinate tutples where there are singleton columns"""
        singletons=[(i,j) for i in range(9) for j in range(9) if self.final_values[i][j] == 0 and len(self.possible_values[i][j]) == 1] #If the cell has not been set and only has one possible value
        return singletons
      
    def propagate_change(self, state, row, column, value):
        """Removes a value from the list of possible values for unassigned cells in the same row, column or 3x3 grid"""
       #Same row and column
        for i in range(0,9):
            if state.possible_values[row][i]!= None and value in state.possible_values[row][i]:
                state.possible_values[row][i].remove(value) #Removes the set value as a possible value
            if state.possible_values[i][column]!= None and value in state.possible_values[i][column]:
                state.possible_values[i][column].remove(value)
            
        #3 by 3
        lower = (row // 3) * 3
        upper = lower + 3
        for new_r in range(lower, upper):
            lower = (column // 3) * 3
            upper = lower + 3
            for new_c in range(lower, upper):
                if state.possible_values[new_r][new_c]!= None and value in state.possible_values[new_r][new_c]:
                    state.possible_values[new_r][new_c].remove(value)
        return state

    def is_possible_to_set(self, row, column, value):
        """Returns false if a value is already in the same row, column or 3x3 grid"""
        # Cannot set value if found the same row, column or 3x3 
        for i in range(0,9):
            if value == self.final_values[row][i] and i!= column:
                return False
            if value == self.final_values[i][column] and i!= row:
                return False
            
        #3 by 3
        lower = (row//3) * 3
        upper = lower + 3
        for new_r in range(lower, upper):
            lower = (column//3) * 3
            upper = lower + 3
            for new_c in range(lower, upper):
                if value == self.final_values[new_r][new_c] and new_r != row and new_c != column:
                    return False
        return True
      
    def get_constraint_count(self, row, column, value):
        """Returns a count cells constrained by the assignment of a specific value"""
        
        count = 0
        for i in range(0,9):
            if value in self.possible_values[row][i] and i!= column: #If the value is possible for a cell, then it constraints it
                count +=1
            if value in self.possible_values[i][column] and i!= row:
                count +=1
            
        #3 by 3
        lower = (row//3) * 3
        upper = lower + 3
        for new_r in range(lower, upper):
            lower = (column//3) * 3
            upper = lower + 3
            for new_c in range(lower, upper):
                if value in self.possible_values[new_r][new_c] and new_r != row and new_c != column:
                    count += 1
        return count
      
    def get_degree_count(self, row, column):
        """Returns a count of the number of unassigned cells in the same row, column or 3x3 grid"""
        degree_count = 0
        for i in range(0,9):
            if self.final_values[row][i] == 0 and i!= column:
                degree_count +=1 
            if self.final_values[i][column] == 0 and i!= row:
                degree_count +=1
            
        #3 by 3
        lower = (row//3) * 3
        upper = lower + 3
        for new_r in range(lower, upper):
            lower = (column//3) * 3
            upper = lower + 3
            for new_c in range(lower, upper):
                if self.final_values[new_r][new_c] == 0 and new_r != row and new_c != column:
                    degree_count +=1
        return degree_count
      
    def copy_state(self):
        """Creates and returns a copy Sudoku object"""
        state = Sudoku(np.ndarray.copy(self.final_values))  #Sets the final_values attribute
        for (row, col), v in np.ndenumerate(self.possible_values): #Sets the possible_values attribute
            state.possible_values[row][col] = v[:]  
        return state  
      
      
    def set_values(self, row, column, value):
        """Sets a value in the board and propagates the changes for possible values"""
        if value not in self.possible_values[row][column]:
            raise ValueError(f"{value} is not a valid choice for cell {row},{column}")
          
        state = self.copy_state() #Not to affect the original state
        state.possible_values[row][column] = [value]
        state.final_values[row][column] = value #Assign value
         
        state = self.propagate_change(state, row, column, value) #Propagatge changes to other cells
                    
        singleton_positions = state.get_singleton_positions() #Sorts the singletons until there are not anymore
        while len(singleton_positions) > 0:
            p = singleton_positions[0]
            r = p[0]
            c = p[1]
            state = state.set_values(r,c, state.possible_values[r][c][0])
            singleton_positions = state.get_singleton_positions()
        return state

In [6]:
def initial_constraints(partial_state):
    """Sets the initial possible values of unsassigned cells by removing values already in the board"""
    values = [1,2,3,4,5,6,7,8,9]
    for i in range(9):
        for j in range(9):
            if partial_state.get_final_values(i,j) == 0: #Empty cell
                possible_vals = [v for v in values if partial_state.is_possible_to_set(i,j,v)] #Can set v in that cell
                partial_state.set_possible_values(i,j,possible_vals)
            else:
                partial_state.set_possible_values(i,j,[-1]) #Possible value is -1
    
    return partial_state
        
def initial_valid(partial_state):
    """Checks if the initial state of the sudoku is valid"""
    for i in range(9):
        for j in range(9):
            val = partial_state.get_final_values(i,j)
            if val != 0 and not partial_state.is_possible_to_set(i,j,val): #Any repeats in the same row, column or 3x3
                return False 
    return True
      
def pick_next_cell(partial_state): 
    """Picks the next cell to be assigned using minimum remaining value and degree heuristic"""
    positions = [(i,j) for i in range(9) for j in range(9) if partial_state.get_final_values(i,j) == 0] #Empty cells to be set
    position = positions[0]
    min = len(partial_state.get_possible_values(*position))

    for p in positions:
        lenght_possible_values = len(partial_state.get_possible_values(*p))
        if lenght_possible_values < min: #Pick the cell position with the least possible values
            position = p
            min = lenght_possible_values
        elif (lenght_possible_values == min): #If they are equal use the degree heuristic
            position = best_degree(partial_state, position, p)
            min = len(partial_state.get_possible_values(*position))
    return position


def best_degree(partial_state, position1, position2):
    """Returns the position with the highest degree heuristic"""
    first_degree = partial_state.get_degree_count(*position1)
    second_degree = partial_state.get_degree_count(*position2)
    if first_degree > second_degree: #Highest degree 
        return position1
    return position2
      
def order_values(partial_state, r,c):
    """Orders the list of possible values to set using least constraining value heuristic"""
    possible_values = partial_state.get_possible_values(r,c)
    constraint_count = [partial_state.get_constraint_count(r,c,v) for v in possible_values]
    #Order the possible_value based on their constraint_count
    least_constraining_values = [x for _, x in sorted(zip(constraint_count, possible_values))]
    #Pick the value that constraints the fewest other values
    
    return least_constraining_values
  
def depth_first_search(partial_state):
    """Depth first search algorithm to solve the sudoku"""
    position = pick_next_cell(partial_state) #Pick the cell to set
    values = order_values(partial_state, *position) #Order the possible value we cna set that cell to
    
    for v in values: #Set each value and generate a new state
        new_state = partial_state.set_values(*position, v)
        if new_state.is_goal(): # Solution
            return new_state
        if not new_state.is_invalid(): #Incomplete state
            deep_state = depth_first_search(new_state)
            if deep_state is not None and deep_state.is_goal():
                return deep_state
    return None
     
def sudoku_solver(sudoku):
    """Solves a Sudoku puzzle and returns its unique solution."""
    partial_state = Sudoku(np.asarray(sudoku))
    
    if initial_valid(partial_state) is False: #Initially invalid
        goal = np.full((9,9),-1.)
        return goal

    #Reduces the possible values or each unsassigned cell with the given sudoku
    partial_state = initial_constraints(partial_state)            
    goal = depth_first_search(partial_state)
    if goal is None: #No solution
        goal = np.full((9,9),-1.)
    else:
        goal = goal.get_final_state() #Solution
    
    return goal

sudoku_solver(sudoku)


TypeError: only size-1 arrays can be converted to Python scalars

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [7]:
SKIP_TESTS = True

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        total_time=0
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")
            total_time +=end_time-start_time

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        av = total_time / 15
        print(f"Average time for {difficulty} is {av}")
        if count < len(sudokus):
            break
            
if not SKIP_TESTS:
    tests()

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [8]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [ ]:
# This is a TEST CELL. Do not delete or change.